/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'pavel' at '8/6/16 6:32 PM' with Gradle 2.12
 *
 * @author pavel, @date 8/6/16 6:32 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
